version: '3'
networks:
  undef-api-auth:
    name: undef-api-auth
services:
  postgres:
    platform: linux/amd64
    image: postgres
    hostname: postgres
    networks: [ undef-api-auth ]
    container_name: undef-api-auth-postgres
    ports: [ 5432:5432 ]
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: undef-api-auth
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      start_period: 10s

  liquibase:
    platform: linux/amd64
    image: liquibase/liquibase
    hostname: liquibase
    networks: [ undef-api-auth ]
    container_name: undef-api-auth-liquibase
    depends_on: [ postgres ]
    volumes: [ ./db:/liquibase/changelog ]
    command: "bash -c 'liquibase \
                       --url=jdbc:postgresql://postgres:5432/undef-api-auth \
                       --searchPath=/liquibase/changelog \
                       --changeLogFile=changelog.xml \
                       --username=postgres \
                       --password=postgres \
                       --databaseChangeLogTableName=_changelog \
                       --databaseChangeLogLockTableName=_changelog_lock \
                       update'"      